"""
NSE-Specific Configuration
Contains NIFTY 200 stocks categorized by sectors for easy selection
"""

# ==================== SECTOR INDICES ====================

NSE_SECTOR_INDICES = {
    '^NSEBANK': 'Banking',
    '^CNXCAP': 'Capital Market',  # Added
    '^CNXIT': 'IT',
    '^CNXAUTO': 'Auto',
    '^CNXPHARMA': 'Pharma',
    '^CNXFMCG': 'FMCG',
    '^CNXMETAL': 'Metal',
    '^CNXREALTY': 'Realty',
    '^CNXENERGY': 'Energy'
}
# ==================== NIFTY 200 STOCKS BY SECTOR ====================

AUTO_STOCKS = [
    'BAJAJ-AUTO.NS', 'BHARATFORG.NS', 'BOSCHLTD.NS', 'EICHERMOT.NS', 'EXIDEIND.NS',
    'HEROMOTOCO.NS', 'HYUNDAI.NS', 'M&M.NS', 'MARUTI.NS', 'MOTHERSON.NS',
    'MRF.NS', 'SONACOMS.NS', 'TIINDIA.NS', 'TMPV.NS', 'TVSMOTOR.NS',
]

CAPITAL_GOODS_STOCKS = [
    'ABB.NS', 'APLAPOLLO.NS', 'ASHOKLEY.NS', 'ASTRAL.NS', 'BDL.NS',
    'BEL.NS', 'BHEL.NS', 'CGPOWER.NS', 'COCHINSHIP.NS', 'CUMMINSIND.NS',
    'ENRIN.NS', 'HAL.NS', 'KEI.NS', 'MAZDOCK.NS', 'POLYCAB.NS',
    'POWERINDIA.NS', 'PREMIERENE.NS', 'SIEMENS.NS', 'SUPREMEIND.NS', 'SUZLON.NS',
    'WAAREEENER.NS',
]

CEMENT_STOCKS = [
    'ACC.NS', 'AMBUJACEM.NS', 'GRASIM.NS', 'SHREECEM.NS', 'ULTRACEMCO.NS',
]

CHEMICAL_STOCKS = [
    'COROMANDEL.NS', 'PIDILITIND.NS', 'PIIND.NS', 'SOLARINDS.NS', 'SRF.NS',
    'UPL.NS',
]

CONSTRUCTION_STOCKS = [
    'IRB.NS', 'LT.NS', 'RVNL.NS',
]

CONSUMER_DURABLES_STOCKS = [
    'ASIANPAINT.NS', 'BLUESTARCO.NS', 'DIXON.NS', 'HAVELLS.NS', 'KALYANKJIL.NS',
    'TITAN.NS', 'VOLTAS.NS',
]

CONSUMER_SERVICES_STOCKS = [
    'DMART.NS', 'ETERNAL.NS', 'INDHOTEL.NS', 'IRCTC.NS', 'ITCHOTELS.NS',
    'JUBLFOOD.NS', 'NAUKRI.NS', 'NYKAA.NS', 'SWIGGY.NS', 'TRENT.NS',
    'VMM.NS',
]

ENERGY_STOCKS = [
    'ADANIENSOL.NS', 'ADANIGREEN.NS', 'ADANIPOWER.NS', 'ATGL.NS', 'BPCL.NS',
    'COALINDIA.NS', 'GAIL.NS', 'HINDPETRO.NS', 'IGL.NS', 'IOC.NS',
    'JSWENERGY.NS', 'NHPC.NS', 'NTPC.NS', 'NTPCGREEN.NS', 'OIL.NS',
    'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'TATAPOWER.NS', 'TORNTPOWER.NS',
]

FINANCIAL_SERVICES_STOCKS = [
    '360ONE.NS', 'ABCAPITAL.NS', 'AUBANK.NS', 'AXISBANK.NS', 'BAJAJFINSV.NS',
    'BAJAJHFL.NS', 'BAJAJHLDNG.NS', 'BAJFINANCE.NS', 'BANKBARODA.NS', 'BANKINDIA.NS',
    'BSE.NS', 'CANBK.NS', 'CHOLAFIN.NS', 'FEDERALBNK.NS', 'HDFCAMC.NS',
    'HDFCBANK.NS', 'HDFCLIFE.NS', 'HUDCO.NS', 'ICICIBANK.NS', 'ICICIGI.NS',
    'IDFCFIRSTB.NS', 'INDIANB.NS', 'INDUSINDBK.NS', 'IREDA.NS', 'IRFC.NS',
    'JIOFIN.NS', 'KOTAKBANK.NS', 'LICHSGFIN.NS', 'LICI.NS', 'LTF.NS',
    'M&MFIN.NS', 'MFSL.NS', 'MOTILALOFS.NS', 'MUTHOOTFIN.NS', 'PAYTM.NS',
    'PFC.NS', 'PNB.NS', 'POLICYBZR.NS', 'RECLTD.NS', 'SBICARD.NS',
    'SBILIFE.NS', 'SBIN.NS', 'SHRIRAMFIN.NS', 'UNIONBANK.NS', 'YESBANK.NS',
]

FMCG_STOCKS = [
    'BRITANNIA.NS', 'COLPAL.NS', 'DABUR.NS', 'DUMMYHDLVR.NS', 'GODFRYPHLP.NS',
    'GODREJCP.NS', 'HINDUNILVR.NS', 'ITC.NS', 'MARICO.NS', 'NESTLEIND.NS',
    'PATANJALI.NS', 'TATACONSUM.NS', 'UNITDSPR.NS', 'VBL.NS',
]

IT_STOCKS = [
    'COFORGE.NS', 'HCLTECH.NS', 'INFY.NS', 'KPITTECH.NS', 'LTIM.NS',
    'MPHASIS.NS', 'OFSS.NS', 'PERSISTENT.NS', 'TATAELXSI.NS', 'TATATECH.NS',
    'TCS.NS', 'TECHM.NS', 'WIPRO.NS',
]

METAL_STOCKS = [
    'ADANIENT.NS', 'HINDALCO.NS', 'HINDZINC.NS', 'JINDALSTEL.NS', 'JSWSTEEL.NS',
    'NATIONALUM.NS', 'NMDC.NS', 'SAIL.NS', 'TATASTEEL.NS', 'VEDL.NS',
]

PHARMA_STOCKS = [
    'ALKEM.NS', 'APOLLOHOSP.NS', 'AUROPHARMA.NS', 'BIOCON.NS', 'CIPLA.NS',
    'DIVISLAB.NS', 'DRREDDY.NS', 'FORTIS.NS', 'GLENMARK.NS', 'LUPIN.NS',
    'MANKIND.NS', 'MAXHEALTH.NS', 'SUNPHARMA.NS', 'TORNTPHARM.NS', 'ZYDUSLIFE.NS',
]

REALTY_STOCKS = [
    'DLF.NS', 'GODREJPROP.NS', 'LODHA.NS', 'OBEROIRLTY.NS', 'PHOENIXLTD.NS',
    'PRESTIGE.NS',
]

SERVICES_STOCKS = [
    'ADANIPORTS.NS', 'CONCOR.NS', 'GMRAIRPORT.NS', 'INDIGO.NS',
]

TELECOM_STOCKS = [
    'BHARTIARTL.NS', 'BHARTIHEXA.NS', 'IDEA.NS', 'INDUSTOWER.NS', 'TATACOMM.NS',
]

TEXTILE_STOCKS = [
    'PAGEIND.NS',
]

DIVERSIFIED_STOCKS = [] # Placeholder if needed

# ==================== CATEGORIZED STOCK GROUPS ====================

STOCK_CATEGORIES = {
    '🚗 Auto': AUTO_STOCKS,
    '⚙️ Capital Goods': CAPITAL_GOODS_STOCKS,
    '🏭 Cement': CEMENT_STOCKS,
    '🧪 Chemicals': CHEMICAL_STOCKS,
    '🏗️ Construction': CONSTRUCTION_STOCKS,
    '🏠 Consumer Durables': CONSUMER_DURABLES_STOCKS,
    '🛍️ Consumer Services': CONSUMER_SERVICES_STOCKS,
    '⚡ Energy': ENERGY_STOCKS,
    '🛒 FMCG': FMCG_STOCKS,
    '🏦 Financial Services': FINANCIAL_SERVICES_STOCKS,
    '💻 IT & Tech': IT_STOCKS,
    '⚒️ Metals': METAL_STOCKS,
    '💊 Pharma': PHARMA_STOCKS,
    '🏘️ Real Estate': REALTY_STOCKS,
    '💼 Services': SERVICES_STOCKS,
    '📱 Telecom': TELECOM_STOCKS,
    '裙 Textiles': TEXTILE_STOCKS,
}

# ==================== NIFTY 200 COMPLETE LIST ====================
NIFTY_200 = (
    '360ONE.NS', 'ABB.NS', 'ABCAPITAL.NS', 'ACC.NS', 'ADANIENSOL.NS',
    'ADANIENT.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'ALKEM.NS',
    'AMBUJACEM.NS', 'APLAPOLLO.NS', 'APOLLOHOSP.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS',
    'ASTRAL.NS', 'ATGL.NS', 'AUBANK.NS', 'AUROPHARMA.NS', 'AXISBANK.NS',
    'BAJAJ-AUTO.NS', 'BAJAJFINSV.NS', 'BAJAJHFL.NS', 'BAJAJHLDNG.NS', 'BAJFINANCE.NS',
    'BANKBARODA.NS', 'BANKINDIA.NS', 'BDL.NS', 'BEL.NS', 'BHARATFORG.NS',
    'BHARTIARTL.NS', 'BHARTIHEXA.NS', 'BHEL.NS', 'BIOCON.NS', 'BLUESTARCO.NS',
    'BOSCHLTD.NS', 'BPCL.NS', 'BRITANNIA.NS', 'BSE.NS', 'CANBK.NS',
    'CGPOWER.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'COALINDIA.NS', 'COCHINSHIP.NS',
    'COFORGE.NS', 'COLPAL.NS', 'CONCOR.NS', 'COROMANDEL.NS', 'CUMMINSIND.NS',
    'DABUR.NS', 'DIVISLAB.NS', 'DIXON.NS', 'DLF.NS', 'DMART.NS',
    'DRREDDY.NS', 'DUMMYHDLVR.NS', 'EICHERMOT.NS', 'ENRIN.NS', 'ETERNAL.NS',
    'EXIDEIND.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'GAIL.NS', 'GLENMARK.NS',
    'GMRAIRPORT.NS', 'GODFRYPHLP.NS', 'GODREJCP.NS', 'GODREJPROP.NS', 'GRASIM.NS',
    'HAL.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'HDFCAMC.NS', 'HDFCBANK.NS',
    'HDFCLIFE.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS',
    'HINDZINC.NS', 'HUDCO.NS', 'HYUNDAI.NS', 'ICICIBANK.NS', 'ICICIGI.NS',
    'IDEA.NS', 'IDFCFIRSTB.NS', 'IGL.NS', 'INDHOTEL.NS', 'INDIANB.NS',
    'INDIGO.NS', 'INDUSINDBK.NS', 'INDUSTOWER.NS', 'INFY.NS', 'IOC.NS',
    'IRB.NS', 'IRCTC.NS', 'IREDA.NS', 'IRFC.NS', 'ITC.NS',
    'ITCHOTELS.NS', 'JINDALSTEL.NS', 'JIOFIN.NS', 'JSWENERGY.NS', 'JSWSTEEL.NS',
    'JUBLFOOD.NS', 'KALYANKJIL.NS', 'KEI.NS', 'KOTAKBANK.NS', 'KPITTECH.NS',
    'LICHSGFIN.NS', 'LICI.NS', 'LODHA.NS', 'LT.NS', 'LTF.NS',
    'LTIM.NS', 'LUPIN.NS', 'M&M.NS', 'M&MFIN.NS', 'MANKIND.NS',
    'MARICO.NS', 'MARUTI.NS', 'MAXHEALTH.NS', 'MAZDOCK.NS', 'MFSL.NS',
    'MOTHERSON.NS', 'MOTILALOFS.NS', 'MPHASIS.NS', 'MRF.NS', 'MUTHOOTFIN.NS',
    'NATIONALUM.NS', 'NAUKRI.NS', 'NESTLEIND.NS', 'NHPC.NS', 'NMDC.NS',
    'NTPC.NS', 'NTPCGREEN.NS', 'NYKAA.NS', 'OBEROIRLTY.NS', 'OFSS.NS',
    'OIL.NS', 'ONGC.NS', 'PAGEIND.NS', 'PATANJALI.NS', 'PAYTM.NS',
    'PERSISTENT.NS', 'PFC.NS', 'PHOENIXLTD.NS', 'PIDILITIND.NS', 'PIIND.NS',
    'PNB.NS', 'POLICYBZR.NS', 'POLYCAB.NS', 'POWERGRID.NS', 'POWERINDIA.NS',
    'PREMIERENE.NS', 'PRESTIGE.NS', 'RECLTD.NS', 'RELIANCE.NS', 'RVNL.NS',
    'SAIL.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SBIN.NS', 'SHREECEM.NS',
    'SHRIRAMFIN.NS', 'SIEMENS.NS', 'SOLARINDS.NS', 'SONACOMS.NS', 'SRF.NS',
    'SUNPHARMA.NS', 'SUPREMEIND.NS', 'SUZLON.NS', 'SWIGGY.NS', 'TATACOMM.NS',
    'TATACONSUM.NS', 'TATAELXSI.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TATATECH.NS',
    'TCS.NS', 'TECHM.NS', 'TIINDIA.NS', 'TITAN.NS', 'TMPV.NS',
    'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TRENT.NS', 'TVSMOTOR.NS', 'ULTRACEMCO.NS',
    'UNIONBANK.NS', 'UNITDSPR.NS', 'UPL.NS', 'VBL.NS', 'VEDL.NS',
    'VMM.NS', 'VOLTAS.NS', 'WAAREEENER.NS', 'WIPRO.NS', 'YESBANK.NS',
    'ZYDUSLIFE.NS',
)


# ==================== PRESET WATCHLISTS ====================

PRESET_WATCHLISTS = {
    'NIFTY 200': list(NIFTY_200),

    'Top 20 by Market Cap': [
        'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS',
        'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
        'LT.NS', 'AXISBANK.NS', 'BAJFINANCE.NS', 'MARUTI.NS', 'HCLTECH.NS',
        'SUNPHARMA.NS', 'NTPC.NS', 'ULTRACEMCO.NS', 'ADANIENT.NS', 'ONGC.NS'
    ],

    'High Growth Mid-Caps': [
        'KAYNES.NS', 'DIXON.NS', 'POLYCAB.NS', 'DMART.NS', 'ASTRAL.NS',
        'ETERNAL.NS', 'NYKAA.NS', 'FLUOROCHEM.NS', 'CAMS.NS', 'ZYDUSLIFE.NS',
        'PAGEIND.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'MPHASIS.NS', 'LTTS.NS',
        'GODREJPROP.NS', 'PRESTIGE.NS', 'OBEROIRLTY.NS', 'PHOENIXLTD.NS', 'BRIGADE.NS'
    ],

    'Banking & Finance': [
        'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'KOTAKBANK.NS', 'AXISBANK.NS',
        'INDUSINDBK.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'HDFCLIFE.NS', 'SBILIFE.NS',
        'ICICIGI.NS', 'HDFCAMC.NS', 'CHOLAFIN.NS', 'MUTHOOTFIN.NS', 'BANDHANBNK.NS',
        'FEDERALBNK.NS', 'IDFCFIRSTB.NS', 'PNB.NS', 'BANKBARODA.NS', 'AUBANK.NS'
    ],

    'IT & Digital': [
        'TCS.NS', 'INFY.NS', 'HCLTECH.NS', 'WIPRO.NS', 'TECHM.NS',
        'LTIM.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'MPHASIS.NS', 'LTTS.NS',
        'TATAELXSI.NS', 'ETERNAL.NS', 'NYKAA.NS', 'PAYTM.NS', 'IRCTC.NS',
        'BHARTIARTL.NS', 'TATACOMM.NS', 'DIXON.NS', 'KAYNES.NS', 'POLYCAB.NS'
    ],

    'Dividend Aristocrats': [
        'ITC.NS', 'HINDUNILVR.NS', 'COALINDIA.NS', 'NTPC.NS', 'POWERGRID.NS',
        'VEDL.NS', 'NMDC.NS', 'ONGC.NS', 'IOC.NS', 'BPCL.NS',
        'HINDZINC.NS', 'SBIN.NS', 'ICICIBANK.NS', 'HDFCBANK.NS', 'TATASTEEL.NS',
        'JSWSTEEL.NS', 'HINDALCO.NS', 'BHARTIARTL.NS', 'MARICO.NS', 'DABUR.NS'
    ],

    'Swing Trading Favorites': [
        'RELIANCE.NS', 'ASIANPAINT.NS', 'TATASTEEL.NS', 'JSWSTEEL.NS', 'BAJFINANCE.NS',
        'AXISBANK.NS', 'ICICIBANK.NS', 'MARUTI.NS', 'M&M.NS', 'LT.NS',
        'SUNPHARMA.NS', 'DRREDDY.NS', 'BHARTIARTL.NS', 'ADANIENT.NS', 'VEDL.NS',
        'HINDALCO.NS', 'ULTRACEMCO.NS', 'GRASIM.NS', 'INDUSINDBK.NS', 'BAJAJ-AUTO.NS'
    ]
}


# ==================== VALIDATION ====================

def get_stocks_by_category(category_name):
    """Get stocks for a specific category"""
    return STOCK_CATEGORIES.get(category_name, [])


def get_preset_watchlist(preset_name):
    """Get stocks for a preset watchlist"""
    return PRESET_WATCHLISTS.get(preset_name, [])


def validate_nse_config():
    """Validate NSE configuration"""
    print(f"✅ NSE Config loaded")
    print(f"   Total stocks in NIFTY 200: {len(NIFTY_200)}")
    print(f"   Categories available: {len(STOCK_CATEGORIES)}")
    print(f"   Preset watchlists: {len(PRESET_WATCHLISTS)}")

    # Check for duplicates
    if len(NIFTY_200) != len(set(NIFTY_200)):
        print("⚠️  Warning: Duplicate stocks found in NIFTY_200")

    return True


# Auto-validate on import
validate_nse_config()